### ISSUE TITLE
papermc-dockerに移行

### ISSUE THREAD

**Issue by sksat** [sksat/mc.yohane.su#20]
[papermc-docker](https://github.com/sksat/papermc-docker)がいいかんじになってきたので．これでイメージの管理が分離できる上にrenovateが使える．

renovate使うなら`1.17.1`みたいなタグはアップデートされていくのでdigestも指定する．

- docker-compose.yml
```yaml
services:
  paper:
    image: ghcr.io/sksat/papermc-docker:1.17.1@sha256:b26d57b32d230fdfbfa6007a2425b52e88ff22981aabe2ce282e31cc3346267c
```
